"""
Reports and Data Export Endpoints.
Provides comprehensive situation reports in JSON, Markdown, and GeoJSON formats.
"""
from datetime import datetime, timezone
from fastapi import APIRouter, Response
from backend.app.pipeline import pipeline_state, PipelineOrchestrator
from backend.app.config import settings

router = APIRouter(prefix="/reports", tags=["Reports & Exports"])


@router.get("")
def get_situation_report():
    """Generates a comprehensive situation assessment report."""
    if pipeline_state.last_processed is None:
        PipelineOrchestrator().run(pipeline_state.current_aoi)

    aoi_cfg = settings.get_aoi_config(pipeline_state.current_aoi)

    critical_villages = [v.name for v in pipeline_state.village_summaries if v.alert_state == "CRITICAL"]
    warning_villages = [v.name for v in pipeline_state.village_summaries if v.alert_state == "WARNING"]

    return {
        "report_title": f"SH-304 Early Warning Situation Report — {aoi_cfg.name}",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "aoi": {
            "id": pipeline_state.current_aoi,
            "name": aoi_cfg.name,
            "center": aoi_cfg.center,
        },
        "operating_mode": settings.mode.upper(),
        "summary": {
            "total_settlements_analyzed": len(pipeline_state.village_summaries),
            "critical_settlements_count": len(critical_villages),
            "critical_settlements": critical_villages,
            "warning_settlements_count": len(warning_villages),
            "warning_settlements": warning_villages,
            "lead_time_status": pipeline_state.lead_time.status if pipeline_state.lead_time else "UNKNOWN",
            "estimated_lead_hours": pipeline_state.lead_time.estimated_lead_time_hours if pipeline_state.lead_time else None,
        },
        "lead_time_assessment": pipeline_state.lead_time.model_dump() if pipeline_state.lead_time else None,
        "backtest_summary": pipeline_state.backtest_results.model_dump() if pipeline_state.backtest_results else None,
        "villages": [v.model_dump() for v in pipeline_state.village_summaries],
        "active_alerts": [a.model_dump() for a in pipeline_state.alerts],
        "disclaimer": (
            "This report is generated by the SH-304 hyper-local data-fusion prototype. "
            "Evacuation notices are SIMULATED for early-warning evaluation. Consult official GSI and IMD bulletins."
        ),
    }


@router.get("/markdown")
def get_markdown_report():
    """Returns downloadable Markdown report format."""
    rep = get_situation_report()
    md = f"""# {rep['report_title']}
*Generated: {rep['generated_at']} | Mode: {rep['operating_mode']}*

## Executive Summary
- **Total Settlements Assessed:** {rep['summary']['total_settlements_analyzed']}
- **Critical Settlements:** {rep['summary']['critical_settlements_count']} ({', '.join(rep['summary']['critical_settlements'])})
- **Warning Settlements:** {rep['summary']['warning_settlements_count']} ({', '.join(rep['summary']['warning_settlements'])})
- **Lead-Time Status:** {rep['summary']['lead_time_status']} (Estimated: ~{rep['summary']['estimated_lead_hours']} hrs)

## Settlement Risk Matrix
| Village | Peak Landslide Risk | Peak Flash Flood Risk | Alert Level | Dominant Driver | Action |
|---|:---:|:---:|:---:|---|---|
"""
    for v in rep['villages']:
        md += f"| {v['name']} | {v['max_landslide_risk']} | {v['max_flash_flood_risk']} | {v['alert_state']} | {v['dominant_factor']} | {v['recommended_action'][:50]}... |\n"

    md += f"\n## Scientific Limitations\n{rep['disclaimer']}\n"

    return Response(content=md, media_type="text/markdown")
